# Generated by Django 4.1.4 on 2022-12-21 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=250, unique=True)),
                ("email", models.EmailField(max_length=250, unique=True)),
                ("password", models.CharField(max_length=250)),
            ],
        ),
    ]
