# Generated by Django 4.1.4 on 2022-12-23 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rollic_backend", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="username",
            new_name="name",
        ),
    ]
